### ISSUE TITLE
打包成功，上传蒲公英没有成功

### ISSUE THREAD

**Issue by andi911** [carya/Util#15]
** EXPORT SUCCEEDED **

cleaned archiveFile: /Users/hsx770911126.com/Desktop/BaoBiao3/autobuild/保镖.xcarchive
ipaPath:~/Desktop/保镖2017-12-06_09-06-28/DistributionSummary.plist
ExportOptions.plist
Packaging.log
保镖.ipa
Traceback (most recent call last):
  File "autobuild.py", line 164, in <module>
    main()
  File "autobuild.py", line 161, in main
    xcbuild(options)
  File "autobuild.py", line 148, in xcbuild
    buildWorkspace(workspace, scheme)
  File "autobuild.py", line 132, in buildWorkspace
    uploadIpaToPgyer(ipaPath)
  File "autobuild.py", line 50, in uploadIpaToPgyer
    files = {'file': open(ipaPath, 'rb')}
IOError: [Errno 2] No such file or directory: u'/Users/hsx770911126.com/Desktop/\u4fdd\u95562017-12-06_09-06-28/DistributionSummary.plist\nExportOptions.plist\nPackaging.log\n\u4fdd\u9556.ipa'

**Comment by shijianmei** [comment]
我也是这个问题,同问

**Comment by chaoxcheng** [comment]
def getIpaPath(exportPath, scheme):
    ipaName = archiveName = "%s.ipa" %(scheme)
    ipaPath = exportPath + "/" + ipaName
    return ipaPath 
修改这个方法, 然后PYGER_PASSWORD 和 PGYDESC 不能是空(也可以直接删除代码中的, 如果不需要填的话), 就可以上传成功了
